In [12]:
# Importing dataset about breast cancer
from sklearn.datasets import load_breast_cancer

# Importing 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier as knn

# Importing default libs
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data_lbc = load_breast_cancer()

print(data_lbc.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [3]:
X = data_lbc.data
y = data_lbc.target

X,y

(array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [4]:
print(X.shape)
print(y.shape)

(569, 30)
(569,)


In [11]:
df = pd.DataFrame(data_lbc.data, columns=data_lbc.feature_names)
df['target'] = pd.Series(data_lbc.target)

df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                   0.07871  ...          17.33           184.60      2019.0   
1                   0.05667  ...          23.41           158.80      1956.0   
2                   0.05999  ...          25.53           152.50      1709.0   
3                   0.09744  ...          26.50            98.87       567.7   
4                   0.05883  ...          16.67           152.20      1575.0   
..                      ...  ...            ...              ...         ...   
564                 0.05623  ...          26.40           166.10      2027.0   
565                 0.05533  ...          38.25           155.00      1731.0   
566                 0.05648  ...          34.12           126.70      1124.0   
567                 0.07016  ...          39.42           184.60      1821.0   
568                 0.05884  ...          30.37            59.16       268.6   

     worst smoothness  worst compactness  worst concavity  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     worst concave points  worst symmetry  worst fractal dimension  target  
0                  0.2654          0.4601                  0.11890       0  
1                  0.1860          0.2750                  0.08902       0  
2                  0.2430          0.3613                  0.08758       0  
3                  0.2575          0.6638                  0.17300       0  
4                  0.1625          0.2364                  0.076

In [7]:
df.describe()

mean radius  mean texture  mean perimeter    mean area  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       mean smoothness  mean compactness  mean concavity  mean concave points  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       mean symmetry  mean fractal dimension  ...  worst texture  \
count     569.000000              569.000000  ...     569.000000   
mean        0.181162                0.062798  ...      25.677223   
std         0.027414                0.007060  ...       6.146258   
min         0.106000                0.049960  ...      12.020000   
25%         0.161900                0.057700  ...      21.080000   
50%         0.179200                0.061540  ...      25.410000   
75%         0.195700                0.066120  ...      29.720000   
max         0.304000                0.097440  ...      49.540000   

       worst perimeter   worst area  worst smoothness  worst compactness  \
count       569.000000   569.000000        569.000000         569.000000   
mean        107.261213   880.583128          0.132369           0.254265   
std          33.602542   569.356993          0.022832           0.157336   
min          50.410000   185.200000          0.071170           0.027290   
25%          84.110000   515.300000          0.116600           0.147200   
50%          97.660000   686.500000          0.131300           0.211900   
75%         125.400000  1084.000000          0.146000           0.339100   
max         251.200000  4254.000000          0.222600           1.058000   

       worst concavity  worst concave points  worst symmetry  \
count       569.000000            569.000000      569.000000   
mean          0.272188              0.114606        0.290076   
std           0.208624              0.065732        0.061867   
min           0.000000              0.000000        0.156500   
25%           0.114500              0.064930        0.250400   
50%           0.226700              0.099930        0.282200   
75%           0.382900              0.161400        0.317900   
max           1.252000              0.291000        0.663800   

       worst fractal dimension      target  
count               569.000000  569.000000  
mean                  0.083946    0.627417  
std                   0.018061    0.483918  
min                   0.055040    0.000000  
25%                   0.071460    0.000000  
50%                   0.080040    1.000000  
75%                   0.092080    1.000000  
max                   0.207500    1.000000  

[8 rows x 31 columns]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [21]:
# Separation in test and train

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, test_size=0.3)

# Seeing shapes

print('X length:', X.shape)
print('y length:', y.shape)
print('X_train length:', X_train.shape)
print('y_train length:', y_train.shape)
print('X_test length:', X_test.shape)
print('y_test length:', y_test.shape)

X length: (569, 30)
y length: (569,)
X_train length: (398, 30)
y_train length: (398,)
X_test length: (171, 30)
y_test length: (171,)


In [18]:
print(np.stack(np.unique(y_test, return_counts=True), axis=1))
print(np.stack(np.unique(y_train, return_counts=True), axis=1))

[[  0  63]
 [  1 108]]
[[  0 149]
 [  1 249]]


In [7]:
df_train_X = pd.DataFrame(X_train, columns=data_lbc.feature_names)
df_test_X = pd.DataFrame(X_test, columns=data_lbc.feature_names)

df_train_X

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0         11.490         14.59           73.99      404.9          0.10460   
1         10.490         18.61           66.86      334.3          0.10680   
2         12.250         17.94           78.27      460.3          0.08654   
3         18.310         18.58          118.60     1041.0          0.08588   
4          6.981         13.43           43.79      143.5          0.11700   
..           ...           ...             ...        ...              ...   
393       18.810         19.98          120.90     1102.0          0.08923   
394       12.460         24.04           83.97      475.9          0.11860   
395        9.436         18.32           59.82      278.6          0.10090   
396        9.720         18.22           60.73      288.1          0.06950   
397       11.510         23.93           74.52      403.5          0.09261   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.08228         0.05308              0.01969         0.1779   
1             0.06678         0.02297              0.01780         0.1482   
2             0.06679         0.03885              0.02331         0.1970   
3             0.08468         0.08169              0.05814         0.1621   
4             0.07568         0.00000              0.00000         0.1930   
..                ...             ...                  ...            ...   
393           0.05884         0.08020              0.05843         0.1550   
394           0.23960         0.22730              0.08543         0.2030   
395           0.05956         0.02710              0.01406         0.1506   
396           0.02344         0.00000              0.00000         0.1653   
397           0.10210         0.11120              0.04105         0.1388   

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.06574  ...        12.400          21.90   
1                   0.06600  ...        11.060          24.54   
2                   0.06228  ...        13.590          25.22   
3                   0.05425  ...        21.310          26.36   
4                   0.07818  ...         7.930          19.54   
..                      ...  ...           ...            ...   
393                 0.04996  ...        19.960          24.30   
394                 0.08243  ...        15.090          40.68   
395                 0.06959  ...        12.020          25.02   
396                 0.06447  ...         9.968          20.83   
397                 0.06570  ...        12.480          37.16   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0              82.04       467.6           0.13520            0.20100   
1              70.76       375.4           0.14130            0.10440   
2              86.60       564.2           0.12170            0.17880   
3             139.20      1410.0           0.12340            0.24450   
4              50.41       185.2           0.15840            0.12020   
..               ...         ...               ...                ...   
393           129.00      1236.0           0.12430            0.11600   
394            97.65       711.4           0.18530            1.05800   
395            75.79       439.6           0.13330            0.10490   
396            62.25       303.8           0.07117            0.02729   
397            82.28       474.2           0.12980            0.25170   

     worst concavity  worst concave points  worst symmetry  \
0            0.25960               0.07431          0.2941   
1            0.08423               0.06528          0.2213   
2            0.19430               0.08211          0.3113   
3            0.35380               0.15710          0.3206   
4            0.00000               0.00000          0.2932   
..               ...                   ...             ...   
393          0.22100               0.12940         